services:
  apiserver:
    depends_on:
      minio_dev:
        condition: service_started
      ensurereplicaset:
        condition: service_completed_successfully
      ensureunprivilegeduser:
        condition: service_completed_successfully
    hostname: api.tournabyte.com
    build:
      context: .
      dockerfile: Dockerfile.webapi
      tags:
        - apidemo
      args:
        GIT_BRANCH: patch-config
    restart: no
    volumes:
      - ../etc/tournabyte/webapi.json:/etc/tournabyte/webapi.json
    secrets:
      - token_signing_key
      - mongo_username
      - mongo_password
      - minio_access_id
      - minio_access_key
      - tls_certificate
      - tls_keychain
secrets:
  token_signing_key:
    file: ../.env/JWT_SECRET_KEY.txt
  mongo_username:
    file: ../.env/API_DB_USERNAME.txt
  mongo_password:
    file: ../.env/API_DB_PASSWORD.txt
  minio_access_id:
    file: ../.env/API_S3_ACCESS_ID.txt
  minio_access_key:
    file: ../.env/API_S3_ACCESS_KEY.txt
  tls_keychain:
    file: ../.env/API_TLS_KEYCHAIN.txt
  tls_certificate:
    file: ../.env/API_TLS_CERTIFICATE.txt
