services:
  appserver:
    depends_on:
      - apiserver
    hostname: app.tournabyte.com
    build:
      context: .
      dockerfile: Dockerfile.webui
      tags:
        - appdemo
      args:
        GIT_BRANCH: main
    restart: no
